spring:
  data:
    redis:
      host: redis
      port: 6379

binance:
  url: https://api.binance.com/api/v3/ticker/price

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
